apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: user02
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: user02
  template:
    metadata:
      labels:
        app: user02
    spec:
      containers:
      - name: user02-server
        image: ghcr.io/ditsayakuls/microservice2
        imagesPullPolicy: Always
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: user02-service
  labels:
    app: user02-service 
spec:
  selector:
    app: user02
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP