apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: microservice2
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
      - name: microservice2-server
        image: ghcr.io/ditsayakuls/microservice2
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: microservice2-service
  labels:
    app: microservice2-service 
spec:
  selector:
    app: microservice2
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP